

#ifndef TIMER_0_CFG_H_
#define TIMER_0_CFG_H_

#define OVERFLOW				255
#define SYSTEM_FREQUENCY		8
#define COMPARE_MATCH_VALUE 	200

/*
Options:
Normal
PWM_PHASE_CORRECT
CTC
FAST_PWM
*/
#define MODE  FAST_PWM
/*
Options:
(Non-PWM Mode)
OC0_DISCONNECTED
OC0_TOGGLE
OC0_CLEAR
OC0_SET

(Fast PWM Mode)
OC0_DISCONNECTED
OC0_CLEAR_ON_COMPARE
OC0_SET_ON_COMPARE

(Phase Correct PWM Mode)
OC0_DISCONNECTED
OC0_CLEAR_UP_COUNT_SET_DOWN_COUNT
OC0_SET_UP_COUNT_CLEAR_DOWN_COUNT

*/
#define COMPARE_OUT_MODE	OC0_CLEAR_ON_COMPARE

/*Options:
NO_CLK_SOURCE
NO_PRESACLING
DIV_8
DIV_64
DIV_256
DIV_1024
EXT_SRC_FALLING_EDGE
EXT_SRC_RISING_EDGE
*/
#define PRESCALER		DIV_8


#define INTERRUPT_OVERFLOW			Enable
#define INTERRUPT_COMPARE_MATCH		Enable

#endif /* TIMER_0_CFG_H_ */